create sequence actor_seq;
create table actor (
  actor_id integer generated by default as sequence actor_seq primary key,
  first_name character varying(255) not null,
  last_name character varying(255) null,
  last_update timestamp not null
);

create table film (
  film_id integer identity,
  title character varying(255) not null,
  release_year integer,
  language_id integer not null ,
  original_language_id integer,
  length integer,
  rating character varying (255),
  last_update timestamp not null,
  special_features varchar(255) array
);

create table language (
  language_id integer identity,
  name character varying(255) not null,
  last_update timestamp not null
);

create table film_actor (
  film_id integer not null,
  actor_id integer not null,
  last_update timestamp not null,
  primary key(film_id, actor_id)
)
